FROM kaggle/python-gpu-build


RUN pip install --upgrade pip
#RUN conda update conda

## https://qiita.com/neko-desu/items/3a9ff96e200073e59101
## 
RUN pip install jupyter_contrib_nbextensions
RUN jupyter contrib nbextension install --user
RUN jupyter contrib nbextension install 


RUN jupyter nbextensions_configurator enable
RUN jupyter nbextensions_configurator enable --user
#RUN pip install jupyter_nbextensions_configurator

RUN pip install fugashi==1.1.0 ipadic==1.0.0


RUN jupyter nbextension enable codefolding/main
#RUN jupyter contrib nbextensions migrate
#RUN conda install anaconda-nb-extensions -c anaconda-nb-extensions

RUN apt-get install -y sudo

## ユーザ作成
#ARG DOCKER_UID=1000
#ARG DOCKER_USER=docker
#ARG DOCKER_PASSWORD=docker
#RUN useradd -m --uid ${DOCKER_UID} --groups sudo ${DOCKER_USER} \
#  && echo ${DOCKER_USER}:${DOCKER_PASSWORD} | chpasswd

# 作成したユーザーに切り替える
USER ${DOCKER_USER}

#
COPY kaggle.json /home/jupyter/.kaggle/kaggle.json
RUN chmod 600 /home/jupyter/.kaggle/kaggle.json
## GPU監視用スクリプト起動
#COPY setup.sh /setup.sh
#RUN chmod 744 /setup.sh  



CMD ["/setup.sh &"]
